name: Deploy Quarto to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v7

      - name: Install quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Jupyter
        run: python3 -m pip install jupyter

      - name: Build Slides
        run: quarto render slides.qmd --no-clean --output-dir output

      - name: Build Poster
        run: quarto render poster.qmd --noclean --output-dir output

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
